#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-tinytest
Version  : 1.1.0
Release  : 1
URL      : https://cran.r-project.org/src/contrib/tinytest_1.1.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/tinytest_1.1.0.tar.gz
Summary  : Lightweight and Feature Complete Unit Testing Framework
Group    : Development/Tools
License  : GPL-3.0
BuildRequires : buildreq-R

%description
### A brief overview of `tinytest`
#### Package setup
A quick way to set things up is as follows.

%prep
%setup -q -c -n tinytest

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1580965678

%install
export SOURCE_DATE_EPOCH=1580965678
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library tinytest
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library tinytest
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library tinytest
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc tinytest || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/tinytest/DESCRIPTION
/usr/lib64/R/library/tinytest/INDEX
/usr/lib64/R/library/tinytest/Meta/Rd.rds
/usr/lib64/R/library/tinytest/Meta/features.rds
/usr/lib64/R/library/tinytest/Meta/hsearch.rds
/usr/lib64/R/library/tinytest/Meta/links.rds
/usr/lib64/R/library/tinytest/Meta/nsInfo.rds
/usr/lib64/R/library/tinytest/Meta/package.rds
/usr/lib64/R/library/tinytest/Meta/vignette.rds
/usr/lib64/R/library/tinytest/NAMESPACE
/usr/lib64/R/library/tinytest/NEWS
/usr/lib64/R/library/tinytest/R/tinytest
/usr/lib64/R/library/tinytest/R/tinytest.rdb
/usr/lib64/R/library/tinytest/R/tinytest.rdx
/usr/lib64/R/library/tinytest/doc/index.html
/usr/lib64/R/library/tinytest/doc/tinytest_examples.R
/usr/lib64/R/library/tinytest/doc/tinytest_examples.Rnw
/usr/lib64/R/library/tinytest/doc/tinytest_examples.pdf
/usr/lib64/R/library/tinytest/doc/using_tinytest.R
/usr/lib64/R/library/tinytest/doc/using_tinytest.Rnw
/usr/lib64/R/library/tinytest/doc/using_tinytest.pdf
/usr/lib64/R/library/tinytest/help/AnIndex
/usr/lib64/R/library/tinytest/help/aliases.rds
/usr/lib64/R/library/tinytest/help/paths.rds
/usr/lib64/R/library/tinytest/help/tinytest.rdb
/usr/lib64/R/library/tinytest/help/tinytest.rdx
/usr/lib64/R/library/tinytest/html/00Index.html
/usr/lib64/R/library/tinytest/html/R.css
/usr/lib64/R/library/tinytest/tests/tinytest.R
/usr/lib64/R/library/tinytest/tinytest/programming.R
/usr/lib64/R/library/tinytest/tinytest/runs/test_cwd.R
/usr/lib64/R/library/tinytest/tinytest/runs/test_cwd2.R
/usr/lib64/R/library/tinytest/tinytest/runs/test_envvar.R
/usr/lib64/R/library/tinytest/tinytest/runs/test_envvar2.R
/usr/lib64/R/library/tinytest/tinytest/runs/test_exit.R
/usr/lib64/R/library/tinytest/tinytest/test_RUnit_style.R
/usr/lib64/R/library/tinytest/tinytest/test_env_A.R
/usr/lib64/R/library/tinytest/tinytest/test_env_B.R
/usr/lib64/R/library/tinytest/tinytest/test_extensibility.R
/usr/lib64/R/library/tinytest/tinytest/test_file.R
/usr/lib64/R/library/tinytest/tinytest/test_gh_issue_17.R
/usr/lib64/R/library/tinytest/tinytest/test_gh_issue_32.R
/usr/lib64/R/library/tinytest/tinytest/test_init.R
/usr/lib64/R/library/tinytest/tinytest/test_tiny.R
/usr/lib64/R/library/tinytest/tinytest/test_utils.R
/usr/lib64/R/library/tinytest/tinytest/women.csv
